### ISSUE TITLE
the directions to install uasyncio are unclear

### ISSUE THREAD

**Issue by safetyfactorman** [hjiawei/micropython-snap#13]
Thank you for all your hard work!!!  

Is there a reason why uasyncio is not included in the linux version?  Is this true for windoze and mac also?  Is there any plan to include it at a future date?

**Comment by hjiawei** [comment]
Thank you for using micropython snap @safetyfactorman. This is more of a question for the [upstream micropython](https://github.com/micropython/micropython/issues). This repository is a unofficial re-packaging of the [micropython unix port](https://github.com/micropython/micropython/tree/master/ports/unix). I tried to maintain this build as close as the upstream.

Meanwhile, I believe you can copy the [uasyncio package](https://github.com/micropython/micropython/tree/master/extmod/uasyncio) together with your project to use it.

**Comment by safetyfactorman1** [comment]
Thanks for your response!  I looked at /snap/micropython on my machine.  There is a /159 dir, and /current dir.  Where exactly do I copy the github code to?  Into /current/bin?  Where does the micropython binary expect to see modules? Thanks in advance!

**Comment by hjiawei** [comment]
I believe you can copy the entire uasyncio folder from the [official micropython repository](https://github.com/micropython/micropython/tree/master/extmod/uasyncio) into your own project source tree. For example, something like this:

```
my-awesome-mpy-uasyncio-project/
├── main.py  # your main entry point
└── uasyncio
    ├── core.py
    ├── event.py
    ├── funcs.py
    ├── __init__.py
    ├── lock.py
    ├── manifest.py
    ├── stream.py
    └── task.py
```

If you really want to install them into the snap folder, the folder structure may look like this (I am using the snap folder under `$HOME`; not the root `/snap` folder):

```
$HOME/snap/micropython/current/.micropython/lib/uasyncio/
├── core.mpy
├── __init__.mpy
├── task.mpy
...
```

The `current` folder is a symbolic link to the latest build/revision folder. micropython snap stable build is at rev 159 at the moment.

**Comment by safetyfactorman1** [comment]
Thank you, thank you, thank you very much sir!
